image: ubuntu:16.04

stages:
  - build_qemu
  - release

before_script:
   - apt-get update -qq

build_qemu:
  stage: build_qemu
  script:
    - apt-get install -y -qq wget git e2fsprogs mtools build-essential gcc-arm-linux-gnueabi libglib2.0-dev zlib1g-dev dh-autoreconf flex bison > /dev/null
    - stuff/building/axiom_beta_build_image_Ubuntu.sh
  artifacts:
    paths:
      - quemu-xlnx.git/
  
  cache:
    untracked: true